### ISSUE TITLE
[I-09] Standard governor voters are incentivized to vote as soon as possible

### ISSUE THREAD

**Issue by k1rill-fedoseev** [MZero-Labs/ttg#174]
## [I-09] Standard governor voters are incentivized to vote as soon as possible

Standard governor voters and delegates receive `POWER` and `ZERO` each epoch once they've voted on all of the pending
proposals in the given epoch. The rewards in `POWER` are locked until the transfer half-epoch starts, and therefore will
unlock for everyone at the same time. `ZERO` rewards, however, are made to be available instantly. This may become
problematic, as the governance participants are now incentivized to vote sooner, which may negatively affect the quality
of made decisions.

Consider paying out all `ZERO` rewards at the end of the epoch similar to `POWER` inflation rewards.

**Comment by toninorair** [comment]
This option was picked to incentivize early voting and simplify logic of ZERO rewards distribution to delegates
